name: doks-kubectl
author: Stephen M. Coakley <me@stephencoakley.com>
description: GitHub action for DigitalOcean Managed Kubernetes (DOKS) that securely connects to a cluster and runs a kubectl command.
inputs:
  access_token:
    description: DigitalOcean access token
    required: true
  cluster:
    description: Kubernetes cluster name or ID
    required: true
  kubectl_version:
    description: Kubectl version to use
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  icon: droplet
  color: blue
